RHsyseng/rhcos-slb

custom-config.fcc
@phoracek @RamLavi 
Mount device use kargs to set the storage location for the mac_address file , 
new command will search for the boot device that is set to save the file, will help in not being depended on new OCP installation location
=> Mount boot device using label

mco_ovs_supervisor.yml.tmpl, mco_ovs_workers.yml.tmpl, setup-ovs.sh
Recent changes in OCP/CoreOS cause the OVS config to get lost in between reboots. This change will delete the OvS bridge if it exists before recreating them. This will now happen on every boot.
=> working around changes in OCP 4.7.x

setup-ovs.sh
As per [bz1899745](https://bugzilla.redhat.com/show_bug.cgi?id=1899745#c2) the MAC should be set for the ovs-interface, not the ovs-bridge, to prevent a race condition.
=> Configuring `802-3-ethernet.cloned-mac-address` on the ovs-interface

README.md, tests/test-coreos.sh
Adding a new test script that will run related coreos ci tests
with the current set-ovs.sh script
Running this before each PR will help us achive better
resiliance and ci repo integrity
=> ci, Add ci using coreos ci

tests/test-coreos.sh
This PR performs some refactoring in order to create a junit.xml from the test.tap already created by the coreos-ci
=> ci, Add junit.xml

tests/test-coreos.sh
The grep seems to sometimes miss the failure. Fix to check grep output
explicitly
=> [simplify-networking] ci, Fix fail condition

tests/test-coreos.sh
Currently when the test fails the scripts stops without printing
the error message. Allow the test to continue allows for a better
log output.
=> tests, Allow the test to continue in fail case

README.md, capture-macs.sh, custom-config.fcc.tmpl, tests/test-coreos.sh
Currently the captured-macs is hard coded to the ignition file.
This makes it annoying to test separately from the ignition file.
Detaching the script from ignition.
Renaming the ignition to .tmpl
Refactoring the README to guide how to create the fcc from the
fcc.tmpl file.
Adjusting the ci to do the same.
=> [simplify-networking] Detach captured macs from ignition

tests/network.go
Recently gitActions takes 10 times longer per test (~10 minutes)
Increasing the timeout to 20 minutes.
=> [simplify-networking] tests, Increase ci test timeout

tests/test-coreos.sh
tests, handle /boot mount race issues in cosa-ci
In cosa-ci the /boot is artificially mounted in
read-only mode. This behavior is different from how it
is mounted on PXE server, and as a result capture-mac's
independently 'mount /boot' command races with the
regular but read-only boot mount.
Instead, depend on the latter, then remount it read-write
in a mount namespace
This commit mimics a similar fix commit in cosa-ci [0]
[0] coreos/coreos-assembler#2328
=> [simplify-networking] capture-macs, Fix /boot mount handling

README.md, init-interfaces.sh, mco_ovs_supervisor.yml.tmpl, mco_ovs_workers.yml.tmpl, tests/network.go, tests/test-coreos.sh
This PR introduces a script that will be run by MCO, and will configure the basic networking needed for future kuberenetes-nmstate manifest deployment.
=> [simplify-networking] interfaces, Set configure interfaces script

init-interfaces.sh
When the connection is down nmcli -g GENERAL.CONNECTION dev show enx525400f68002 is empty,
we can put it up but with ipv4/ipv6 disabled so we can use the nmcli command also,
when the connection is down the "description" field cannot be updated.
=> init-interfaces: Enable secondary nic

add-slb-nncp.yaml, del-slb-nncp.yaml, init-interfaces.sh, kcli/README.md, kcli/add-slb.sh, kcli/del-slb.sh, kcli/deploy-knmstate.sh, kcli/ocp.yaml, kcli/retry.sh, kcli/update-keepalived.sh
This PR add the final part to configure the OVS SLB using kubernetes-nmstate it also contains needed integration with kcli so it can be tested.
=> [simplify-networking] Use kubernetes-nmstate to configure OVS SLB bond

add-slb-nncp.yaml, del-slb-nncp.yaml, kcli/add-slb.sh
When the NNCP is applied towards a cluster configured with the previous
script the NNCP fails since the ovs-interface was named brcnv and at the
NNCP is brcnv-iface. This change keep the brcnv name to the
ovs-interface since nmstate supports interfaces with same name.
=> nncp: Keep the brcnv name for the ovs-interface

mco_ovs_supervisor.yml.tmpl, mco_ovs_workers.yml.tmpl, tests/network.go
Due to the renaming of setup-ovs.service to init-interfaces.service,
newly installed clusters fail with the following:
Failed to disable unit: Unit file setup-ovs.service does not exist.
That is due to us trying to disable a service that was never installed
as a unit file.
This patch works around it by keeping the old service name.
Signed-off-by: Petr Horáček <phoracek@redhat.com>
=> Keep the old name of the service

init-interfaces.sh
The current way of detecting profiles is not working reliably during
boot. The existing version of get_con_name_by_device is unable to
detect deactivated profiles associated to the device. That leads to the
profile of not being found, we create our own and then conflict with the
old profile getting activated.
This brings back commit ef360ae6d1fc11562c074a1c270766edfe7f5fe1 except
it drops code that introduced explicit MAC settings on profiles we create.
Signed-off-by: Petr Horáček <phoracek@redhat.com>
=> Detect deactivated profiles based on name/mac

init-interfaces.sh
To be sure that the MAC address is present at the keyfile this file
enforce it when interface is set up.
From the reverted commit [1]
[1] https://github.com/RHsyseng/rhcos-slb/commit/ef360ae6d1fc11562c074a1c270766edfe7f5fe1#diff-0c94eb0760c378a3b22ac5f205d9b3312b528ff954fe82d077a897f5fec9b06cR107
Signed-off-by: Enrique Llorente <ellorent@redhat.com>
=> init-interfaces: Enforce MAC address

tests/test-coreos.sh
In case we run from a non clean environment
=> Run fetch before reset

.github/workflows/weeklyci.yml
In order to prevent CI to broken by third party dependants like coreos-coreos-assembler repo, adding a weekly ci check.
=> ci, Add weekely CI Test

.github/workflows/weeklyci.yml
This Pr fixes a typo in the cron job parameters and project name
=> fix typo in weeklyci

init-interfaces.sh
When the secondary connection exists but not activated, Adding command to make sure that the parameters of the connections are as expected.
=> Make sure the interface match our expected state

.github/workflows/ci.yml, .github/workflows/weeklyci.yml
One of the dependencies in the gitActions workflows is swtpm. As ubuntu-latest recently moved to 22.04 [0], it is now not complient with the swtpm supported ubuntu vertions [1].
Pinning to a supportd version ubuntu 20.04.
[0] actions/runner-images#6776
[1] https://launchpad.net/~smoser/+archive/ubuntu/swtpm
=> [main] weeklyci, ci, swtpm: Pin workflow to ubuntu 20.4
